rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby
  - rbx
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
    - rvm: jruby
notifications:
  recipients:
    - xrkhill@gmail.com
  irc: "irc.freenode.org#guard"
