rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - rbx
  - jruby
matrix:
  allow_failures:
    - rvm: rbx-2.2.10
notifications:
  recipients:
    - xrkhill@gmail.com
  irc: "irc.freenode.org#guard"
